### ISSUE TITLE
Oppdatere veilederen slik at den er for DCAT-AP-NO v.2.0

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dcat-ap-no-implementering#2]
Nåværende versjon veilederen var utarbeidet for DCAT-AP-NO v.1.1 som er under utfasing.

**Comment by KjerstiSteien** [comment]
@jimjyang fortsatt relevant? Eller kan denne lukkes?

**Comment by jimjyang** [comment]
Veilederen er utgått og vil ikke bli vedlikeholdt lenger.

Lukkes.
